/**Info 211 Fall 2020 Team One
 * Zack Clevenger
 * Angela Johnson
 * Amber Ferrebee
 */
package insultSelector;

/**
 *
 * @author amber
 */
public class UseShakespeareGUI extends javax.swing.JFrame {
double userChoice = 0.0;
QuestionsAnswers[] QandA = new QuestionsAnswers[10];
Insults[] insultChoices = new Insults[10];
double[] answers = new double[10];
int i = 0;

    /**
     * Creates new form UseShakespeareGUI
     */
    public UseShakespeareGUI() {
        initComponents();
    }
    public void refreshQuestion(){
                String I1 = "If you spend word for word with me, I shall make your wit bankrupt.\n (Two Gentlemen of Verona, Act 2, Scene 4)";
		String I2 = "It is a tale told by an idiot, full of sound and fury, signifying nothing.\n (Macbeth, Act 5, Scene 5)";
		String I3 = "More of your conversation would infect my brain.\n (Coriolanus, Act 2, Scene 1)";
		String I4 = "Your brain is as dry as the remainder biscuit after voyage.\n (As You Like It, Act 2, Scene 7)";
		String I5 = "Thy tongue outvenoms all the worms of Nile.\n (Cymbeline, Act 3, Scene 4)";
		String I6 = "I do desire that we may be better strangers.\n (As You Like It, Act 3, Scene 2)";
		String I7 = "There’s no more faith in thee than in a stewed prune.\n (Henry IV Part 1, Act 3, Scene 3)";
		String I8 = "Thou cream faced loon!\n (Macbeth. Act 5, Scene 3)";
		String I9 = "Thou art a boil, a plague sore, an embossed carbuncle in my corrupted blood.\n (King Lear, Act 2, Scene 4)";
		String I10 = "Thou sodden-witted lord! Thou hast no more brain than I have in mine elbows!\n (Troilus and Cressida, Act 2, Scene 1)";
		
		String q1 =  "Question 1:  \nThis villan has the intelligence of...\n 1: A box of crayons, minus the crayons\n 2: A bowl of rancid tapioca. "
				+ "\n 3: A cat's left toe.\n";
		String q2 = "Question 2:  \nYour adversary is as attractive as...\n 1: An infected boil.\n 2: A newly expunged hairball. \n 3: Three day old roadkill.\n";
		String q3 = "Question 3:  \nTrusting this person makes as much sense as...\n 1: Peeing on an electric fence. \n 2: Attempting to take a fish from a hungry bear. \n "
				+ "3: Beliving Flat-Earthers' theories.\n";
		String q4 = "Question 4:  \nWhen they speak, they sound like...\n 1: A fainting goat.\n 2: Acrylic nails meeting a chalkboard.\n "
				+ "3: A bassoon with bronchitis\n";
		String q5 = "Question 5:  \nYour opponent smells of...\n 1: Elderberries. \n 2: A rotting carcass.\n 3: Horse manure, freshly squeezed.\n";
		String q6 = "Question 6:  \nThe briefest look at your rival's face...\n 1: Turns you to stone. \n 2: Causes your eyes to hemorrhage \n "
				+ "3: puts you in mind of an infants's post-grape drink poo.\n";
		String q7 = "Question 7:  \nYour opponant's eyes bare an uncanny resemblance to...\n 1: An empty nest - no one is home. \n 2: The vaccuum of space - forever emply and lifeless.\n "
				+ "3: Rotten stewed and skinned tomatoes.\n";
		String q8 = "Question 8:  \nYour enemy's wit...\n 1: Is as dull as a rusty spoon. \n 2: Would bore a dead fish.\n "
				+ "3: Makes Mad Libs look like high literature. \n";
		String q9 = "Question 9:  \nYour enemy's smile...\n 1: Makes 11th century dental work look progressive. \n 2: Has as much scum as a stagnant swamp."
				+ "\n 3: Overused and overwhitened.\n";
		String q10 = "Question 10:  \nIn your opinion, your competetor is...\n 1: A very good waste of air. \n 2: A prime example of the failure of Darwin's theories."
				+ "\n 3: A pox upon everyone's houses.\n";
		
		Insults[] insultChoices = {
				new Insults(I1),
				new Insults(I2),
				new Insults(I3),
				new Insults(I4),
				new Insults(I5),
				new Insults(I6),
				new Insults(I7),
				new Insults(I8),
				new Insults(I9),
				new Insults(I10),
		};

		QuestionsAnswers[] QandA = {
				new QuestionsAnswers(q1),
				new QuestionsAnswers(q2),
				new QuestionsAnswers(q3),
				new QuestionsAnswers(q4),
				new QuestionsAnswers(q5),
				new QuestionsAnswers(q6),
				new QuestionsAnswers(q7),
				new QuestionsAnswers(q8),
				new QuestionsAnswers(q9),
				new QuestionsAnswers(q10)
		};
        
        if(i < 10){
            jTextArea1.setText(QandA[i].question);

        }
        
        else {
            int sum = AnalyseAnswers.sumAnswers(answers);
            double ave = AnalyseAnswers.averageOFAnswers(sum);
            int insNumber = AnalyseAnswers.random();
            jLabel3.setText(Choices.pickIntro(ave));
            jLabel4.setText(Choices.pickInsult(insultChoices, insNumber));           
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setForeground(new java.awt.Color(0, 0, 0));
        setLocation(new java.awt.Point(300, 150));

        jLabel1.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Shakespearean Insult Selector");
        jLabel1.setOpaque(true);

        jButton1.setBackground(new java.awt.Color(174, 187, 218));
        jButton1.setFont(new java.awt.Font("Goudy Stout", 0, 18)); // NOI18N
        jButton1.setText("1");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(174, 187, 218));
        jButton2.setFont(new java.awt.Font("Goudy Stout", 0, 18)); // NOI18N
        jButton2.setText("2");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(174, 183, 219));
        jButton3.setFont(new java.awt.Font("Goudy Stout", 0, 18)); // NOI18N
        jButton3.setText("3");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel3.setOpaque(true);

        jLabel4.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setOpaque(true);

        jScrollPane1.setBorder(null);

        jTextArea1.setBackground(new java.awt.Color(212, 219, 236));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Goudy Old Style", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Question 1:  \nThis villan has the intelligence of...\n  1: A box of crayons, minus the crayons\\\n  2: A bowl of rancid tapioca. \n  3: A cat's left toe.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        jLabel2.setText("Results:");

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jSeparator1.setOpaque(true);

        jSeparator2.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jSeparator2.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 43, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(261, 261, 261))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 733, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        userChoice = 1.0;
        answers[i] = userChoice;
        i++;
        refreshQuestion();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        userChoice = 2.0;
        answers[i] = userChoice;
        i++;
        refreshQuestion();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        userChoice = 3.0;
        answers[i] = userChoice;
        i++;
        refreshQuestion();
    }//GEN-LAST:event_jButton3ActionPerformed




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
